/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lembredio;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author elrafa
 */
public class FarmaceuticoInterface extends javax.swing.JInternalFrame {
    Farmaceutico Farma = new Farmaceutico();
    String nomeUser;
    String loginUser;
    String nomeFarmacia;
    /**
     * Creates new form FarmaceuticoInterface
     */
    public FarmaceuticoInterface() {
        initComponents();
    }
    
    public FarmaceuticoInterface(Farmaceutico Farma) throws IOException {
        initComponents();
        setVisible(true);
        this.Farma = Farma;
        
        nomeUser = Farma.loginInfo.pessoa.getNome();
       nomeFarmacia = returnNomeFarma();
       jLabel2.setText(nomeFarmacia);
       LabelNomeFarma.setText(nomeUser);
       
       jLabelQuantidade.setVisible(false);
       jLabelPreço.setVisible(false);
       jTextFieldQuantidade.setVisible(false);
       jTextFieldPreço.setVisible(false);
    }
    
     public String returnNomeFarma() throws IOException{
       InputStream is = new FileInputStream("CADASTRADOS.txt");
       InputStreamReader isr = new InputStreamReader(is);
       BufferedReader br = new BufferedReader(isr);

        try {
            String linha;
            int i =0;
          do{

              linha = br.readLine();

              if(linha == null) break;


                switch (Integer.parseInt(linha)) {
                    case 0:
                               for(i=0; i< 4; i++) br.readLine();
                        break;
                    case 1:
                              for(i=0; i< 5; i++) br.readLine();
                        break;
                    case 2:
                        if(br.readLine().equals(Farma.loginInfo.getLogin())){
                            for(i=0; i < 3; i++) br.readLine();

                            String nomefarma = br.readLine();

                            br.close();

                            return nomefarma;
                        }
                        for(i = 0; i < 4; i++) br.readLine();
                        break;
                    default:
                        break;
                }

          }while(linha != null);


        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

       br.close();
       return "";
       //return true;
    }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LabelNomeFarma = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextFieldNomeReme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ButtonSalvar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FormattedTextFieldPU = new javax.swing.JTextField();
        FormattedFieldQuantReme = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabelQuantidade = new javax.swing.JLabel();
        jLabelPreço = new javax.swing.JLabel();
        ButtonAtualizarMed = new javax.swing.JButton();
        jButtonSelecionar = new javax.swing.JButton();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jTextFieldPreço = new javax.swing.JTextField();
        jButtonAtualizarEstoque = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        logoutButton = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        sobre = new javax.swing.JMenuItem();

        setPreferredSize(new java.awt.Dimension(665, 545));

        jLabel5.setText("Farmacêutico(a) :");

        LabelNomeFarma.setText("Nome Farmacêutico(a)");

        jLabel1.setText("Farmácia : ");

        jLabel2.setText("Nome Farmácia");

        jLabel3.setText("Nome do medicamento :");

        TextFieldNomeReme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNomeRemeActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade :");

        ButtonSalvar.setText("Salvar");
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });

        jLabel6.setText("Preço Unitário :");

        jLabel12.setText("R$");

        FormattedFieldQuantReme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormattedFieldQuantRemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelNomeFarma)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldNomeReme, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FormattedTextFieldPU, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FormattedFieldQuantReme, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonSalvar)
                .addGap(144, 144, 144))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LabelNomeFarma)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextFieldNomeReme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FormattedFieldQuantReme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(FormattedTextFieldPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(ButtonSalvar)
                .addGap(35, 35, 35))
        );

        jTabbedPane2.addTab("Cadastrar Remédios", jPanel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicamentos" }));
        jComboBox1.setToolTipText("Medicamentos\n");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Medicamento :");

        jLabelQuantidade.setText("Quantidade :");

        jLabelPreço.setText("Preço :");

        ButtonAtualizarMed.setText("Atualizar Medicamentos");
        ButtonAtualizarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAtualizarMedActionPerformed(evt);
            }
        });

        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        jButtonAtualizarEstoque.setText("Atualizar Estoque");
        jButtonAtualizarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButtonSelecionar)
                        .addGap(38, 38, 38)
                        .addComponent(ButtonAtualizarMed)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonAtualizarEstoque))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelQuantidade)
                            .addComponent(jLabelPreço))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldQuantidade)
                            .addComponent(jTextFieldPreço, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantidade)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPreço)
                    .addComponent(jTextFieldPreço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAtualizarMed)
                    .addComponent(jButtonSelecionar)
                    .addComponent(jButtonAtualizarEstoque))
                .addGap(195, 195, 195))
        );

        jTabbedPane2.addTab("Ver Estoque", jPanel2);

        jMenu2.setText("Arquivo");

        logoutButton.setText("Sair");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jMenu2.add(logoutButton);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Ajuda");

        sobre.setText("Sobre");
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });
        jMenu1.add(sobre);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNomeRemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNomeRemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeRemeActionPerformed

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        File diretorio = new File("EstoqueFarmacias");
        diretorio.mkdir();
        File Estoque = new File(diretorio,nomeFarmacia + ".txt");

        try {
            FileWriter fw = new FileWriter(Estoque, true);
            if(TextFieldNomeReme.getText().length()>0 && FormattedFieldQuantReme.getText().length() > 0 && FormattedTextFieldPU.getText().length() > 0){
                fw.write(TextFieldNomeReme.getText());
                fw.write("\r\n");
                fw.write(FormattedFieldQuantReme.getText());
                fw.write("\r\n");
                fw.write(FormattedTextFieldPU.getText());
                fw.write("\r\n");
                
                fw.flush();
                fw.close();
                
                JOptionPane.showMessageDialog(null,"Remédio Cadastrado com sucesso!");
                
                TextFieldNomeReme.setText("");
                FormattedFieldQuantReme.setText("");
                FormattedTextFieldPU.setText("");
                
            }
            else if(TextFieldNomeReme.getText().length()<=0 || FormattedFieldQuantReme.getText().length() <= 0 || FormattedTextFieldPU.getText().length() <= 0){
                if(TextFieldNomeReme.getText().length()<= 0){
                    JOptionPane.showMessageDialog(null,"Entre com o nome do remédio!");
                }
                if (FormattedFieldQuantReme.getText().length() <= 0){
                    JOptionPane.showMessageDialog(null,"Entre com a quantidade de remédios!");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Entre com o preço!!");
                }
            }
          

        } catch (IOException ex) {
            Logger.getLogger(FarmaceuticoInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonSalvarActionPerformed

    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        

      
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        jTabbedPane2.setVisible(false);
        getParent().remove(jTabbedPane2);
        getParent().setVisible(false);
        getParent().getParent().add(new LoginInterface());
        getParent().remove(this);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreActionPerformed
        JOptionPane.showMessageDialog(null, "\t\tLEMBRÉDIO\t\t\n\tDesenvolvedores:\nMatheus Brito\nRafael Alessandro\n");
    }//GEN-LAST:event_sobreActionPerformed

    private void FormattedFieldQuantRemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormattedFieldQuantRemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormattedFieldQuantRemeActionPerformed

    private void ButtonAtualizarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAtualizarMedActionPerformed
      
     jComboBox1.removeAllItems();
        InputStream is;
        try {
            is = new FileInputStream("EstoqueFarmacias/"+nomeFarmacia+".txt");
        
       InputStreamReader isr = new InputStreamReader(is);
       BufferedReader br = new BufferedReader(isr);

        try {
            String linha;
            int i =0;
          do{

              linha = br.readLine();

              if(linha == null) break;                    
                           String nomeRemedio = linha;
                           jComboBox1.addItem(linha);                  
                           for(i=0; i < 2; i++){
                               linha = br.readLine();
                            
                           }
                            
          }while(linha != null);
           br.close();
            } catch (FileNotFoundException ex) {
            Logger.getLogger(FarmaceuticoInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
     
 
    }//GEN-LAST:event_ButtonAtualizarMedActionPerformed

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        String medicamento = jComboBox1.getSelectedItem().toString();
       
        jLabelQuantidade.setVisible(true);
        jLabelPreço.setVisible(true);
        jTextFieldQuantidade.setVisible(true);
        jTextFieldPreço.setVisible(true);
        
        InputStream is;
        try {
            is = new FileInputStream("EstoqueFarmacias/"+nomeFarmacia+".txt");
        
       InputStreamReader isr = new InputStreamReader(is);
       BufferedReader br = new BufferedReader(isr);

        try {
            String linha;
            int i =0;
          do{

              linha = br.readLine();

              if(linha == null) break;                    
                            if(medicamento.equals(linha)){
                                jTextFieldQuantidade.setText(br.readLine());
                                jTextFieldPreço.setText(br.readLine());
                            }              
                           for(i=0; i < 2; i++){
                               linha = br.readLine();
                           }
                            
          }while(linha != null);
           br.close();
            } catch (FileNotFoundException ex) {
            Logger.getLogger(FarmaceuticoInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    private void jButtonAtualizarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarEstoqueActionPerformed
        String medicamento = jComboBox1.getSelectedItem().toString();
        jLabelQuantidade.setVisible(true);
        jLabelPreço.setVisible(true);
        jTextFieldQuantidade.setVisible(true);
        jTextFieldPreço.setVisible(true);
      
      
        try {
             BufferedWriter wr = new BufferedWriter(new FileWriter("EstoqueFarmacias/"+"arqTemp.txt"));
             BufferedReader br = new BufferedReader(new FileReader("EstoqueFarmacias/"+nomeFarmacia+".txt"));

        try {
            String linha;
            int i =0;
          do{

              linha = br.readLine();
              String qtd = jTextFieldQuantidade.getText();
              String valor = jTextFieldPreço.getText();
              if(linha == null) break;     
              if(medicamento.equals(linha)){
                  wr.write(linha+"\r\n");
                  linha = br.readLine();                  
                         wr.write(qtd + "\r\n");
                         linha = br.readLine(); 
                         wr.write(valor + "\r\n");
                         linha = br.readLine();
                         if(linha == null) break;
              }
                 wr.write(linha + "\r\n");
          }while(linha != null);
          wr.flush();
          wr.close();
          br.close();
           
           new File("EstoqueFarmacias/"+nomeFarmacia+".txt").delete();
           new File("EstoqueFarmacias/"+"arqTemp.txt").renameTo(new File("EstoqueFarmacias/"+nomeFarmacia+".txt")); 
            } catch (FileNotFoundException ex) {
            Logger.getLogger(FarmaceuticoInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAtualizarEstoqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAtualizarMed;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JTextField FormattedFieldQuantReme;
    private javax.swing.JTextField FormattedTextFieldPU;
    private javax.swing.JLabel LabelNomeFarma;
    private javax.swing.JTextField TextFieldNomeReme;
    private javax.swing.JButton jButtonAtualizarEstoque;
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelPreço;
    private javax.swing.JLabel jLabelQuantidade;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldPreço;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JMenuItem logoutButton;
    private javax.swing.JMenuItem sobre;
    // End of variables declaration//GEN-END:variables
}
