package lembredio;


import java.awt.Container;
import java.beans.PropertyVetoException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import lembredio.Login;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author elrafa
 */
public class LoginInterface extends javax.swing.JInternalFrame {
    
    Login vlogin = new Login();
    
    /**
     * Creates new form NovoJInternalFrame
     */
    public LoginInterface() {
        initComponents();
        setVisible(true);
        errorMessage.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagemTelaDeLogin = new javax.swing.JLabel();
        EfetuarCadastro = new javax.swing.JButton();
        EfetuarLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();
        DigitarSenha = new javax.swing.JPasswordField();
        DigitarLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(665, 544));
        setMinimumSize(new java.awt.Dimension(665, 544));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(665, 544));
        setVerifyInputWhenFocusTarget(false);
        setVisible(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });

        ImagemTelaDeLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo - Lembredio-1.png"))); // NOI18N

        EfetuarCadastro.setText("Cadastre-se!");
        EfetuarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EfetuarCadastroActionPerformed(evt);
            }
        });

        EfetuarLogin.setText("Login");
        EfetuarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EfetuarLoginActionPerformed(evt);
            }
        });

        jLabel2.setText("Não tem conta?");

        errorMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1497671163_scull.png"))); // NOI18N
        errorMessage.setText("Login ou Senha incorretos!!!");

        DigitarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitarSenhaActionPerformed(evt);
            }
        });

        DigitarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitarLoginActionPerformed(evt);
            }
        });

        jLabel4.setText("Senha");

        jLabel3.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(errorMessage))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(EfetuarCadastro)
                                .addGap(91, 91, 91)
                                .addComponent(EfetuarLogin))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(12, 30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DigitarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DigitarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ImagemTelaDeLogin)
                .addGap(223, 223, 223))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ImagemTelaDeLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(DigitarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(DigitarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(errorMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EfetuarCadastro)
                    .addComponent(EfetuarLogin))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DigitarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitarLoginActionPerformed
        this.vlogin.setLogin(evt.getActionCommand());
        System.out.println(vlogin.getLogin());
    }//GEN-LAST:event_DigitarLoginActionPerformed

    private void EfetuarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EfetuarLoginActionPerformed
        
        try {
            vlogin.setLogin(DigitarLogin.getText());
            vlogin.setSenha(DigitarSenha.getText());
            
            if(vlogin.verificaLogin()){
             setVisible(false);
             
                switch (vlogin.getType()) {
                    case 0:
                        getParent().add(new PacienteInterface(vlogin.getLogin()));
                        
                        break;
                       
                    case 1:
                        
                        getParent().add(new MedicoInterface(new Médico(vlogin)));
                        break;
                    case 2:
                        getParent().add(new FarmaceuticoInterface(new Farmaceutico(vlogin)));
                        break;
                    default:
                      
                        break;
                }
             
            }else errorMessage.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(LoginInterface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LoginInterface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(LoginInterface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(LoginInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_EfetuarLoginActionPerformed

    private void DigitarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitarSenhaActionPerformed
        
    }//GEN-LAST:event_DigitarSenhaActionPerformed

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        this.setLocation(0, 0);// TODO add your handling code here:
    }//GEN-LAST:event_formComponentMoved

    private void EfetuarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EfetuarCadastroActionPerformed
        setVisible(false);
        try {
            getParent().add(new CadastroInterface());
            getParent().remove(this);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(LoginInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EfetuarCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DigitarLogin;
    private javax.swing.JPasswordField DigitarSenha;
    private javax.swing.JButton EfetuarCadastro;
    private javax.swing.JButton EfetuarLogin;
    private javax.swing.JLabel ImagemTelaDeLogin;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
