package lembredio;


import java.awt.Color;
import java.awt.Component;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author elrafa
 */
public class TelaInicial extends javax.swing.JFrame {
    public LoginInterface obj = new LoginInterface();
    public CadastroInterface obj2 = new CadastroInterface();
        
    /**
     * Creates new form TelaInicial
     */
    
    
    public TelaInicial() throws PropertyVetoException, IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        jDesktopPane3.add(obj);
        obj.setMaximizable(true);
        obj.setMaximum(true);
        obj.setVisible(true);
        getContentPane().setBackground(Color.WHITE);
       
        File file = new File("CADASTRADOS.txt");
       if(!file.exists()){
        file.createNewFile();// TODO code application logic here
       }
       File dir = new File("CadastroRemedios");
       if(!dir.exists()){
           dir.mkdir();
       }
        //this.setExtendedState(MAXIMIZED_BOTH);
        //jDesktopPane3.setExtendedState(MAXIMIZED_BOTH);
       //obj.setLocation(jDesktopPane3.getSize().width/2 - obj.getSize().width/2,jDesktopPane3.getSize().height/2 - obj.getSize().height/2);

    }
    
    public TelaInicial(LoginInterface obj) throws PropertyVetoException, IOException{
        initComponents();
        this.setLocationRelativeTo(null);
        this.obj = obj;
        jDesktopPane3.add(this.obj);
        jDesktopPane3.setVisible(true);
        this.obj.setMaximizable(false);
        this.obj.setMaximum(true);
        this.obj.setVisible(true);
        getContentPane().setBackground(Color.WHITE);
        File file = new File("CADASTRADOS.txt");
       
       if(!file.exists()){
        file.createNewFile();// TODO code application logic here
       }
       File dir = new File("CadastroRemedios");
       if(!dir.exists()){
           dir.mkdir();
       }
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public void addFrame(JInternalFrame JIFrame){
       // jDesktopPane3.remove(this.obj);
        //jDesktopPane3.setVisible(false);
        
    }
    public Component returnComponent(){
        return jDesktopPane3.getComponentAt(getSize().height/2, getSize().width/2);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane3 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lembrédio");
        setBackground(new java.awt.Color(20, 29, 189));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
              File file = new File("CADASTRADOS.txt");
              if(!file.exists()){
               file.createNewFile();// TODO code application logic here
              }
              File dir = new File("CadastroRemedios");
              if(!dir.exists()){
                  dir.mkdir();
              }
                    new TelaInicial().setVisible(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jDesktopPane3;
    // End of variables declaration//GEN-END:variables
}
