package lembredio;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import static java.lang.Thread.sleep;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author elrafa
 */
public class MedicoInterface extends javax.swing.JInternalFrame {
    Login vlogin = new Login();
    int qual=0;
    String nomeUser;
    String loginUser;
    Médico medico;
    
    /**
     * Creates new form MedicoInterface
     */
    
    
    
    public MedicoInterface() throws IOException {
        initComponents();
        setVisible(true); 
       
    }
    
     /*
        Inicializa o nome do médico, coloca a interface de cadastro de remédios como
    invisível, salva o CRM no campo do CRM, mostra os usuário na aba de visualizar usuários
     e mostra as mensagens do médico.
     */
    public MedicoInterface(Médico medico) throws FileNotFoundException, IOException{
        initComponents();
        setVisible(true);
        this.medico = medico;
        
        cadastroRemedioInterface.setVisible(false);
        
        nomeMedico.setText(medico.loginInfo.pessoa.getNome());
        
        qual = -1;
        
        manageUsers();
        int CRM = returnCRM();
        medicoCrm.setText(Integer.toString(CRM));
        setMedicMessages();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abasInterfaceMedico = new javax.swing.JTabbedPane();
        telaInicialMedico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeMedico = new javax.swing.JLabel();
        medicoCrm = new javax.swing.JLabel();
        avisosTextArea = new javax.swing.JTextArea();
        jButtonCriarLembrete = new javax.swing.JButton();
        ButtonLimpar = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        visualizarUsuariosInterface = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        userName4Medic = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userLogin4Medic = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userEmail4Medic = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        userAge4Medic = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        selectUser = new javax.swing.JButton();
        nextUser = new javax.swing.JButton();
        lastUser = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cadastroRemedioInterface = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        nomeRemedio1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CheckDomingo1 = new javax.swing.JCheckBox();
        CheckSegunda1 = new javax.swing.JCheckBox();
        CheckTerça1 = new javax.swing.JCheckBox();
        CheckQuinta1 = new javax.swing.JCheckBox();
        CheckSexta1 = new javax.swing.JCheckBox();
        CheckSabado1 = new javax.swing.JCheckBox();
        CheckQuarta1 = new javax.swing.JCheckBox();
        CheckTDS1 = new javax.swing.JCheckBox();
        horarioRemedio1 = new javax.swing.JFormattedTextField();
        BotaoSalvar1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jComboBox21 = new javax.swing.JComboBox<>();
        jButtonVoltarProcurarPaciente = new javax.swing.JButton();
        menuDeOpcoes = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        logoutButton = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        sobre = new javax.swing.JMenuItem();

        setMaximumSize(new java.awt.Dimension(665, 544));
        setMinimumSize(new java.awt.Dimension(665, 544));
        setPreferredSize(new java.awt.Dimension(665, 554));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jLabel1.setText("Médico:");

        jLabel2.setText("CRM:");

        nomeMedico.setText("Nome do Médico");

        medicoCrm.setText("CRM do Médico");

        avisosTextArea.setColumns(20);
        avisosTextArea.setRows(5);
        avisosTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonCriarLembrete.setText("Criar Lembrete");
        jButtonCriarLembrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarLembreteActionPerformed(evt);
            }
        });

        ButtonLimpar.setText("Limpar");
        ButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaInicialMedicoLayout = new javax.swing.GroupLayout(telaInicialMedico);
        telaInicialMedico.setLayout(telaInicialMedicoLayout);
        telaInicialMedicoLayout.setHorizontalGroup(
            telaInicialMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicialMedicoLayout.createSequentialGroup()
                .addComponent(avisosTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(telaInicialMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeMedico)
                .addGap(175, 175, 175)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medicoCrm)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(telaInicialMedicoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButtonCriarLembrete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonLimpar)
                .addGap(48, 48, 48))
        );
        telaInicialMedicoLayout.setVerticalGroup(
            telaInicialMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicialMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaInicialMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeMedico)
                    .addComponent(jLabel2)
                    .addComponent(medicoCrm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avisosTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaInicialMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCriarLembrete)
                    .addComponent(ButtonLimpar))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        abasInterfaceMedico.addTab("Avisos", telaInicialMedico);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(665, 544));

        visualizarUsuariosInterface.setPreferredSize(new java.awt.Dimension(665, 544));

        jPanel6.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setText("Nome do Paciente:");

        userName4Medic.setText("nomePaciente");

        jLabel5.setText("Login:");

        userLogin4Medic.setText("loginpaciente");

        jLabel7.setText("E-mail:");

        userEmail4Medic.setText("emailPaciente");

        jLabel9.setText("Idade:");

        userAge4Medic.setText("Idadepaciente");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_image.jpg"))); // NOI18N

        selectUser.setText("Selecionar Usuário");
        selectUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(userName4Medic, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(userAge4Medic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectUser)
                                .addContainerGap())))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(67, 67, 67)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userLogin4Medic, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userEmail4Medic))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(userLogin4Medic))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(userEmail4Medic)))
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userName4Medic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userAge4Medic)
                        .addComponent(selectUser)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nextUser.setText("Próximo Usuário");
        nextUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextUserActionPerformed(evt);
            }
        });

        lastUser.setText("Usuário Anterior");
        lastUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastUserActionPerformed(evt);
            }
        });

        jLabel12.setText("Pesquisar Usuário");

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout visualizarUsuariosInterfaceLayout = new javax.swing.GroupLayout(visualizarUsuariosInterface);
        visualizarUsuariosInterface.setLayout(visualizarUsuariosInterfaceLayout);
        visualizarUsuariosInterfaceLayout.setHorizontalGroup(
            visualizarUsuariosInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizarUsuariosInterfaceLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, visualizarUsuariosInterfaceLayout.createSequentialGroup()
                .addGroup(visualizarUsuariosInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(visualizarUsuariosInterfaceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(visualizarUsuariosInterfaceLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lastUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextUser)))
                .addGap(50, 50, 50))
        );
        visualizarUsuariosInterfaceLayout.setVerticalGroup(
            visualizarUsuariosInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizarUsuariosInterfaceLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(visualizarUsuariosInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(okButton))
                .addGap(56, 56, 56)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(visualizarUsuariosInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextUser)
                    .addComponent(lastUser))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        cadastroRemedioInterface.setPreferredSize(new java.awt.Dimension(665, 544));

        jLabel14.setText(" Remédios :");

        jLabel15.setText("Horarios :");

        jLabel16.setText("Dias da Semana :");

        CheckDomingo1.setText("Domingo");

        CheckSegunda1.setText("Segunda - feira");

        CheckTerça1.setText("Terça - feira");

        CheckQuinta1.setText("Quinta - feira");

        CheckSexta1.setText("Sexta - feira");

        CheckSabado1.setText("Sábado");

        CheckQuarta1.setText("Quarta - feira");

        CheckTDS1.setText("Todos os dias da semana");

        try {
            horarioRemedio1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        horarioRemedio1.setToolTipText("");
        horarioRemedio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioRemedio1RemedioActionPerformed(evt);
            }
        });

        BotaoSalvar1.setText("Salvar");
        BotaoSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvar1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Intervalo:");

        jComboBox21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 vez ao dia", "3 em 3 horas", "4 em 4 horas", "6 em 6 horas", "8 em 8 horas", "12 em 12 horas", "1 vez ao dia" }));

        jButtonVoltarProcurarPaciente.setText("Voltar");
        jButtonVoltarProcurarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarProcurarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroRemedioInterfaceLayout = new javax.swing.GroupLayout(cadastroRemedioInterface);
        cadastroRemedioInterface.setLayout(cadastroRemedioInterfaceLayout);
        cadastroRemedioInterfaceLayout.setHorizontalGroup(
            cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroRemedioInterfaceLayout.createSequentialGroup()
                .addGroup(cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroRemedioInterfaceLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroRemedioInterfaceLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(124, 124, 124)
                                .addComponent(nomeRemedio1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadastroRemedioInterfaceLayout.createSequentialGroup()
                                .addGroup(cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(horarioRemedio1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cadastroRemedioInterfaceLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jComboBox21, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(cadastroRemedioInterfaceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroRemedioInterfaceLayout.createSequentialGroup()
                                .addGroup(cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CheckDomingo1)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CheckSegunda1)
                                .addGap(18, 18, 18)
                                .addComponent(CheckTerça1)
                                .addGap(18, 18, 18)
                                .addComponent(CheckQuarta1))
                            .addGroup(cadastroRemedioInterfaceLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(CheckQuinta1)
                                .addGap(18, 18, 18)
                                .addComponent(CheckSexta1)
                                .addGap(18, 18, 18)
                                .addComponent(CheckSabado1)
                                .addGap(18, 18, 18)
                                .addComponent(CheckTDS1))))
                    .addGroup(cadastroRemedioInterfaceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVoltarProcurarPaciente)
                        .addGap(367, 367, 367)
                        .addComponent(BotaoSalvar1)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        cadastroRemedioInterfaceLayout.setVerticalGroup(
            cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroRemedioInterfaceLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nomeRemedio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(horarioRemedio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jLabel16)
                .addGap(35, 35, 35)
                .addGroup(cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckDomingo1)
                    .addComponent(CheckSegunda1)
                    .addComponent(CheckTerça1)
                    .addComponent(CheckQuarta1))
                .addGap(18, 18, 18)
                .addGroup(cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckQuinta1)
                    .addComponent(CheckSexta1)
                    .addComponent(CheckSabado1)
                    .addComponent(CheckTDS1))
                .addGap(29, 29, 29)
                .addGroup(cadastroRemedioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltarProcurarPaciente)
                    .addComponent(BotaoSalvar1))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(visualizarUsuariosInterface, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cadastroRemedioInterface, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastroRemedioInterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(visualizarUsuariosInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastroRemedioInterface, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(visualizarUsuariosInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        abasInterfaceMedico.addTab("Procurar Pacientes", jLayeredPane1);

        jMenu2.setText("Arquivo");

        logoutButton.setText("Sair");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jMenu2.add(logoutButton);

        menuDeOpcoes.add(jMenu2);

        jMenu1.setText("Ajuda");

        sobre.setText("Sobre");
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });
        jMenu1.add(sobre);

        menuDeOpcoes.add(jMenu1);

        setJMenuBar(menuDeOpcoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abasInterfaceMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abasInterfaceMedico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
        Pega o CRM do médico cujo abriu a interface.
    */
    public int returnCRM() throws IOException{
        InputStream is = new FileInputStream("CADASTRADOS.txt");
       InputStreamReader isr = new InputStreamReader(is);
       BufferedReader br = new BufferedReader(isr);
       
        try {
            String linha;
            int i =0;
          do{
            
              linha = br.readLine();
              
              if(linha == null) break;
              
             
                switch (Integer.parseInt(linha)) {
                    case 0:
                               for(i=0; i< 4; i++) br.readLine();
                        break;
                    case 1:
                        if(br.readLine().equals(medico.loginInfo.getLogin())){
                            for(i=0; i < 3; i++) br.readLine();
                            
                            int CRM = Integer.parseInt(br.readLine());
                            
                            br.close();
                            
                            return CRM;
                        }       for(i=0; i< 4; i++) br.readLine();
                        break;
                    case 2:
                               for(i=0; i< 4; i++) br.readLine();
                        break;
                    default:
                        break;
                }
            
          }while(linha != null);

            
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       br.close();
       return -1;
       //return true;
    }
    /*
        Na aba de visualizar usuários, ao clicar no botão de último usuário ele 
    modifica a variável 'qual' que serve para a manipulação dos usuário que serão mostrados.
    */
    private void lastUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastUserActionPerformed
        if(qual > 0){
            qual = qual -2;
            manageUsers();
        }// TODO add your handling code here:
    }//GEN-LAST:event_lastUserActionPerformed
    /*
        Na aba de visualizar usuários, ao clicar no botão de próximo usuário ele 
    simplesmente invoca o método de manipular o que é mostrado na tela..
    */
    private void nextUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextUserActionPerformed
        manageUsers();
    }//GEN-LAST:event_nextUserActionPerformed
    /*
        Ao selecionar o usuário, é mostrado qual o remédio que o médico deseja cadastrar
    para o supracitado e pré-selecionado usuário.
    
    */
    private void selectUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUserActionPerformed
        cadastroRemedioInterface.setVisible(true);
        visualizarUsuariosInterface.setVisible(false);
        
    }//GEN-LAST:event_selectUserActionPerformed
    /*
        Define as mensagens que serão mostradas na página inicial do médico.
    */
    
    public void setMedicMessages() throws FileNotFoundException, IOException{
                File diretorio = new File("LembretesMedicos");
         
        File Recados = new File(diretorio,nomeMedico.getText() + ".txt");
        if(!Recados.exists()) try {
            Recados.createNewFile();
        } catch (IOException ex) {
           Logger.getLogger(MedicoInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        InputStream is;
      
            is = new FileInputStream("LembretesMedicos/" + nomeMedico.getText() +".txt");
            InputStreamReader isr = new InputStreamReader(is);
                BufferedReader br = new BufferedReader(isr);
             String linha = br.readLine();
        while(linha != null){           
            avisosTextArea.append(linha);
            avisosTextArea.append("\n");
            linha = br.readLine();
        }
           
            br.close();
        
    }
    /*
        Faz a pesquisa no arquivo em busca do usuário que foi digitado no campo de busca.
    */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
       InputStream is = null;
        try {
            is = new FileInputStream("CADASTRADOS.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MedicoInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
       InputStreamReader isr = new InputStreamReader(is);
       BufferedReader br = new BufferedReader(isr);
       String temp1, temp2;
        try {
            String linha;
            int i =0;
          do{
            
              linha = br.readLine();
            
              if(linha == null) break;
              
             
                switch (Integer.parseInt(linha)) {
                    case 0:
                        
                           loginUser = br.readLine();
                           br.readLine();
                           nomeUser = br.readLine();
                           if(searchTextField.getText() != "" && nomeUser.equalsIgnoreCase(searchTextField.getText())){
                               temp2 = br.readLine();
                                userLogin4Medic.setText(loginUser);
                                userName4Medic.setText(nomeUser);
                                userEmail4Medic.setText(temp2);
                           br.close();
                           return;
                           
                           }else 
                               for(i=0; i< 1; i++) br.readLine();
                        break;
                    case 1:
                        
                              for(i=0; i< 5; i++) br.readLine();
                        break;
                    case 2:
                             for(i=0; i< 4; i++) br.readLine();
                        break;
                    default:
                        break;
                }
            
          }while(linha != null);

            
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        try {
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(MedicoInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_okButtonActionPerformed

    private void horarioRemedio1RemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioRemedio1RemedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horarioRemedio1RemedioActionPerformed
    /*
        Botão referente à tela de cadastrar remédios, mostrada após selecionar o usuário.
        Salva no arquivo do usuário o remédio receitado pelo médico.
    */
    private void BotaoSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvar1ActionPerformed
        File diretorio = new File("CadastroRemedios");
        diretorio.mkdir();
        File Remedios = new File(diretorio,loginUser + ".txt");
        String ok = (horarioRemedio1.getText());
        String horas[] = new String[2];
        horas = ok.split(Pattern.quote(":"));
        if(Integer.parseInt(horas[0]) > 24 || Integer.parseInt(horas[0]) < 0 && Integer.parseInt(horas[1]) < 0 || Integer.parseInt(horas[1]) > 59){
            JOptionPane.showMessageDialog(null,"Horario inválido!!");
            System.out.println("Horas "+horas[0]+"minutos "+horas[1]);
        }
        else{
            try {
                FileWriter fw = new FileWriter(Remedios, true);
                if(nomeRemedio1.getText().length() > 0 && CheckDomingo1.isSelected()||CheckSegunda1.isSelected()||CheckTerça1.isSelected()||CheckQuarta1.isSelected()||CheckQuinta1.isSelected()||CheckSexta1.isSelected()||CheckSabado1.isSelected()||CheckTDS1.isSelected()){
                    fw.write(loginUser);
                    fw.write("\r\n");
                    fw.write(nomeRemedio1.getText());
                    fw.write("\r\n");

                    //fw.write(ok);
                    fw.write("\r\n");
                    fw.write(jComboBox21.getSelectedItem().toString());
                    fw.write("\r\n");
                    if(CheckDomingo1.isSelected()){
                        fw.write("1");
                        fw.write("\r\n");
                    }
                    if(CheckSegunda1.isSelected()){
                        fw.write("2");
                        fw.write("\r\n");
                    }
                    if(CheckTerça1.isSelected()){
                        fw.write("3");
                        fw.write("\r\n");
                    }
                    if(CheckQuarta1.isSelected()){
                        fw.write("4");
                        fw.write("\r\n");
                    }
                    if(CheckQuinta1.isSelected()){
                        fw.write("5");
                        fw.write("\r\n");
                    }
                    if(CheckSexta1.isSelected()){
                        fw.write("6");
                        fw.write("\r\n");
                    }
                    if(CheckSabado1.isSelected()){
                        fw.write("7");
                        fw.write("\r\n");
                    }
                    if(CheckTDS1.isSelected()){
                        fw.write("1");
                        fw.write("\r\n");
                        fw.write("2");
                        fw.write("\r\n");
                        fw.write("3");
                        fw.write("\r\n");
                        fw.write("4");
                        fw.write("\r\n");
                        fw.write("5");
                        fw.write("\r\n");
                        fw.write("6");
                        fw.write("\r\n");
                        fw.write("7");
                        fw.write("\r\n");

                    }
                    JOptionPane.showMessageDialog(null,"Remédio Cadastrado com sucesso!");

                    nomeRemedio1.setText("");
                    horarioRemedio1.setText("");
                    CheckDomingo1.setSelected(false);
                    CheckDomingo1.setSelected(false);
                    CheckTerça1.setSelected(false);
                    CheckQuarta1.setSelected(false);
                    CheckQuinta1.setSelected(false);
                    CheckSexta1.setSelected(false);
                    CheckSabado1.setSelected(false);
                    CheckTDS1.setSelected(false);

                }
                else{
                    JOptionPane.showMessageDialog(null,"Preencha todos os dados");
                }
                fw.flush();
                fw.close();
                
            } catch (IOException ex) {
                Logger.getLogger(PacienteInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        cadastroRemedioInterface.setVisible(false);
        visualizarUsuariosInterface.setVisible(true);
        }  
    }//GEN-LAST:event_BotaoSalvar1ActionPerformed
    /*
        Botão que retorna à tela de procura de pacientes.
    */
    private void jButtonVoltarProcurarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarProcurarPacienteActionPerformed
        cadastroRemedioInterface.setVisible(false);
       visualizarUsuariosInterface.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarProcurarPacienteActionPerformed
    /*
        Cria um lembrete que o médico digitou na tela, após clicar no botão.
    */
    private void jButtonCriarLembreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarLembreteActionPerformed
        File diretorio = new File("LembretesMedicos");
        diretorio.mkdir();
        File Recados = new File(diretorio,nomeMedico.getText()+ ".txt");
        if(!Recados.exists()) try {
            Recados.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(MedicoInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            FileWriter fw = new FileWriter(Recados, true);
            fw.write( avisosTextArea.getText());
            fw.write("\r\n");
            fw.flush();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(MedicoInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCriarLembreteActionPerformed
    /*
        Limpa da tela o que foi escrito.
    */
    private void ButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimparActionPerformed

       avisosTextArea.setText("");
     
       File diretorio = new File("LembretesMedicos");
         
        File Recados = new File(diretorio,nomeMedico.getText() + ".txt");
        if(!Recados.exists()) try {
            Recados.createNewFile();
       } catch (IOException ex) {
           Logger.getLogger(MedicoInterface.class.getName()).log(Level.SEVERE, null, ex);
       }      
        
        if(Recados.delete()){
            System.out.println("Deu certo");
        }
    }//GEN-LAST:event_ButtonLimparActionPerformed
    /*
        Retorna à tela de login.
    */
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        abasInterfaceMedico.setVisible(false);
        getParent().remove(abasInterfaceMedico);
        getParent().setVisible(false);
        getParent().getParent().add(new LoginInterface());
        getParent().remove(this);
 
       
    }//GEN-LAST:event_logoutButtonActionPerformed
    /*
        Exibe os produtores & desenvolvedores do programa.
    */
    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreActionPerformed
        JOptionPane.showMessageDialog(null, "\t\tLEMBRÉDIO\t\t\n\tDesenvolvedores:\nMatheus Brito\nRafael Alessandro\n");
    }//GEN-LAST:event_sobreActionPerformed
    /*
        Sem dúvidas, o mais 'belo' método que existe aqui. Ele utiliza 
    a variável 'qual' para identificar qual o último usuário visitado e procura no
    arquivo o próximo para ser exibido. Obviamente com algumas manipulações ele pega o último
    usuário e com outras o próximo. Tudo incluso na variável 'qual'.
    */
    public void manageUsers(){
        InputStream is = null;
        try {
            is = new FileInputStream("CADASTRADOS.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MedicoInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
       InputStreamReader isr = new InputStreamReader(is);
       BufferedReader br = new BufferedReader(isr);
       
        try {
            String linha;
            int i=0;
            int l=-1;
          while(true){
            
              linha = br.readLine();
              if(linha==null) break;
                if(Integer.parseInt(linha)==0)l++;
                
                if(Integer.parseInt(linha)==0 && l==qual+1 ) {
                    loginUser = br.readLine();
                    userLogin4Medic.setText(loginUser);
                    br.readLine();
                    userName4Medic.setText(br.readLine());
                    userEmail4Medic.setText(br.readLine());
                    
                    qual++;
                    break;
                            
                 }else if(Integer.parseInt(linha) == 1){
                     for(i=0; i< 5; i++) br.readLine();
                 }
                 else{
                     for(i=0; i< 4; i++) br.readLine();
                 }
                    
                
          }

            
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        try {
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(MedicoInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSalvar1;
    private javax.swing.JButton ButtonLimpar;
    private javax.swing.JCheckBox CheckDomingo1;
    private javax.swing.JCheckBox CheckQuarta1;
    private javax.swing.JCheckBox CheckQuinta1;
    private javax.swing.JCheckBox CheckSabado1;
    private javax.swing.JCheckBox CheckSegunda1;
    private javax.swing.JCheckBox CheckSexta1;
    private javax.swing.JCheckBox CheckTDS1;
    private javax.swing.JCheckBox CheckTerça1;
    private javax.swing.JTabbedPane abasInterfaceMedico;
    private javax.swing.JTextArea avisosTextArea;
    private javax.swing.JPanel cadastroRemedioInterface;
    private javax.swing.JFormattedTextField horarioRemedio1;
    private javax.swing.JButton jButtonCriarLembrete;
    private javax.swing.JButton jButtonVoltarProcurarPaciente;
    private javax.swing.JComboBox<String> jComboBox21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton lastUser;
    private javax.swing.JMenuItem logoutButton;
    private javax.swing.JLabel medicoCrm;
    private javax.swing.JMenuBar menuDeOpcoes;
    private javax.swing.JButton nextUser;
    private javax.swing.JLabel nomeMedico;
    private javax.swing.JTextField nomeRemedio1;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton selectUser;
    private javax.swing.JMenuItem sobre;
    private javax.swing.JPanel telaInicialMedico;
    private javax.swing.JLabel userAge4Medic;
    private javax.swing.JLabel userEmail4Medic;
    private javax.swing.JLabel userLogin4Medic;
    private javax.swing.JLabel userName4Medic;
    private javax.swing.JPanel visualizarUsuariosInterface;
    // End of variables declaration//GEN-END:variables
}
